{% import "macros.j2" as _etcd with context %}
apiVersion: v1
kind: Pod
metadata:
  name: kube-podmaster
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: scheduler-elector
    image: {{podmaster}}
    command:
    - /podmaster
    - --etcd-servers={{_etcd.peers()}}
{% if etcd_ca_setup %}
    - --etcd-ca-file={{_etcd.ca_file()}}
    - --etcd-key-file={{_etcd.key_file()}}
    - --etcd-cert-file={{_etcd.cert_file()}}
{% endif %}
    - --key=scheduler
    - --whoami={{ansible_default_ipv4.address}}
    - --source-file=/src/manifests/kube-scheduler.yaml
    - --dest-file=/dst/manifests/kube-scheduler.yaml
    volumeMounts:
    - mountPath: {{etcd_certs_root}}
      name: etcd-certs
      readOnly: true
    - mountPath: /src/manifests
      name: manifest-src
      readOnly: true
    - mountPath: /dst/manifests
      name: manifest-dst
  - name: controller-manager-elector
    image: {{podmaster}}
    command:
    - /podmaster
    - --etcd-servers={{_etcd.peers()}}
{% if etcd_ca_setup %}
    - --etcd-ca-file={{_etcd.ca_file()}}
    - --etcd-key-file={{_etcd.key_file()}}
    - --etcd-cert-file={{_etcd.cert_file()}}
{% endif %}
    - --key=controller
    - --whoami={{ansible_default_ipv4.address}}
    - --source-file=/src/manifests/kube-controller-manager.yaml
    - --dest-file=/dst/manifests/kube-controller-manager.yaml
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: {{etcd_certs_root}}
      name: etcd-certs
      readOnly: true
    - mountPath: /src/manifests
      name: manifest-src
      readOnly: true
    - mountPath: /dst/manifests
      name: manifest-dst
  volumes:
  - hostPath:
      path: /srv/kubernetes/manifests
    name: manifest-src
  - hostPath:
      path: /etc/kubernetes/manifests
    name: manifest-dst
  - hostPath:
      path: {{etcd_certs_root}}
    name: etcd-certs
